In [2]:
import numpy as np

In [3]:
A = np.array([[0,0,0,1,0,1,1,0,0],[0,0,0,1,1,0,1,0,0],[0,1,1,0,2,0,0,0,0],[1,0,0,0,0,0,0,1,1]])
print('DTM의 크기(shape) :', np.shape(A))

DTM의 크기(shape) : (4, 9)


In [7]:
U, s, VT = np.linalg.svd(A, full_matrices = True)
print('행렬 U : ')
print(U.round(2))
print('행렬 U의 크기(shape) : ', np.shape(U))

행렬 U : 
[[-0.24  0.75  0.   -0.62]
 [-0.51  0.44 -0.    0.74]
 [-0.83 -0.49 -0.   -0.27]
 [-0.   -0.    1.    0.  ]]
행렬 U의 크기(shape) :  (4, 4)


In [8]:
print('특이값 벡터 : ')
print(s.round(2))
print('특이값 벡터의 크기(shape) : ', np.shape(s))

# linalg.svd()는 특이값 분해의 결과로 대각 행렬이 아니라 특이값의 리스트를 반환
# 이를 다시 대각 행렬로 바꿔줘야 한다.

특이값 벡터 : 
[2.69 2.05 1.73 0.77]
특이값 벡터의 크기(shape) :  (4,)


In [9]:
S = np.zeros((4,9))
S[:4, :4] = np.diag(s)

print('대각 행렬 S :')
print(S.round(2))

print('대각 행렬의 크기(shape) : ')
print(np.shape(S))

대각 행렬 S :
[[2.69 0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   2.05 0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   1.73 0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.77 0.   0.   0.   0.   0.  ]]
대각 행렬의 크기(shape) : 
(4, 9)


In [10]:
print('직교행렬 VT : ')
print(VT.round(2))

print('직교 행렬 VT의 크기(shape) : ')
print(np.shape(VT))

직교행렬 VT : 
[[-0.   -0.31 -0.31 -0.28 -0.8  -0.09 -0.28 -0.   -0.  ]
 [ 0.   -0.24 -0.24  0.58 -0.26  0.37  0.58 -0.   -0.  ]
 [ 0.58 -0.    0.    0.   -0.    0.   -0.    0.58  0.58]
 [ 0.   -0.35 -0.35  0.16  0.25 -0.8   0.16 -0.   -0.  ]
 [-0.   -0.78 -0.01 -0.2   0.4   0.4  -0.2   0.    0.  ]
 [-0.29  0.31 -0.78 -0.24  0.23  0.23  0.01  0.14  0.14]
 [-0.29 -0.1   0.26 -0.59 -0.08 -0.08  0.66  0.14  0.14]
 [-0.5  -0.06  0.15  0.24 -0.05 -0.05 -0.19  0.75 -0.25]
 [-0.5  -0.06  0.15  0.24 -0.05 -0.05 -0.19 -0.25  0.75]]
직교 행렬 VT의 크기(shape) : 
(9, 9)


In [11]:
# allclose로 A행렬과 U*S*VT의 행렬이 같은지 확인
np.allclose(A, np.dot(np.dot(U,S), VT).round(2))

True

In [12]:
# t를 정하고 절단된 SVD 수행
# t=2로 가정
# 특이값 상위 2개만 보존
S = S[:2,:2]

print('대각 행렬 S :')
print(S.round(2))

대각 행렬 S :
[[2.69 0.  ]
 [0.   2.05]]


In [13]:
U = U[:,:2]
print('행렬 U :')
print(U.round(2))

행렬 U :
[[-0.24  0.75]
 [-0.51  0.44]
 [-0.83 -0.49]
 [-0.   -0.  ]]


In [14]:
VT = VT[:2,:]
print('직교행렬 VT :')
print(VT.round(2))
# V관점에서는 2개의 열만 남기고 제거한 것이 된다

직교행렬 VT :
[[-0.   -0.31 -0.31 -0.28 -0.8  -0.09 -0.28 -0.   -0.  ]
 [ 0.   -0.24 -0.24  0.58 -0.26  0.37  0.58 -0.   -0.  ]]


In [15]:
A_prime = np.dot(np.dot(U,S), VT)
print(A)
print(A_prime.round(2))

[[0 0 0 1 0 1 1 0 0]
 [0 0 0 1 1 0 1 0 0]
 [0 1 1 0 2 0 0 0 0]
 [1 0 0 0 0 0 0 1 1]]
[[ 0.   -0.17 -0.17  1.08  0.12  0.62  1.08 -0.   -0.  ]
 [ 0.    0.2   0.2   0.91  0.86  0.45  0.91  0.    0.  ]
 [ 0.    0.93  0.93  0.03  2.05 -0.17  0.03  0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.    0.  ]]


U의 각 행은 잠재의미를 표현하기 위한 수치화 된 각각의 문서 벡터
VT의 각 열은 잠재 의미를 표현하기 위한 수치화 된 각각의 단어 벡터

In [ ]:
# LSA를 사용해서 문서의 수를 원하는 토픽의 수로 압축한 뒤에
# 각 토픽당 가장 중요한 단어 5개를 출력하는 실습으로 토픽 모델링 수행

In [1]:
import pandas as pd
from sklearn.datasets import fetch_20newsgroups
import nltk
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD

In [2]:
dataset = fetch_20newsgroups(shuffle=True, random_state=1, remove=
                             ('headers', 'footers', 'quotes'))
documents = dataset.data
print('샘플의 수 : ', len(documents))

샘플의 수 :  11314


In [3]:
# 첫번째 훈련용 샘플
# 뉴스그룹 데이터에는 특수문자가 포함된 다수의 영어문장으로 구성
# scikit-learn이 제공하는 데이터에서 target_name에는 뉴스그룹 데이터가 어떤 20개의 카테고리를
# 갖고 있었는지가 저장되어져 있음
documents[1]

"\n\n\n\n\n\n\nYeah, do you expect people to read the FAQ, etc. and actually accept hard\natheism?  No, you need a little leap of faith, Jimmy.  Your logic runs out\nof steam!\n\n\n\n\n\n\n\nJim,\n\nSorry I can't pity you, Jim.  And I'm sorry that you have these feelings of\ndenial about the faith you need to get by.  Oh well, just pretend that it will\nall end happily ever after anyway.  Maybe if you start a new newsgroup,\nalt.atheist.hard, you won't be bummin' so much?\n\n\n\n\n\n\nBye-Bye, Big Jim.  Don't forget your Flintstone's Chewables!  :) \n--\nBake Timmons, III"

In [4]:
print(dataset.target_names)

['alt.atheism', 'comp.graphics', 'comp.os.ms-windows.misc', 'comp.sys.ibm.pc.hardware', 'comp.sys.mac.hardware', 'comp.windows.x', 'misc.forsale', 'rec.autos', 'rec.motorcycles', 'rec.sport.baseball', 'rec.sport.hockey', 'sci.crypt', 'sci.electronics', 'sci.med', 'sci.space', 'soc.religion.christian', 'talk.politics.guns', 'talk.politics.mideast', 'talk.politics.misc', 'talk.religion.misc']


In [ ]:
# 텍스트 전처리
# 알파벳을 제외한 구두점, 숫자, 특수문자를 제거하는 것
# 정규 표현식을 통해서 해결 가능
# 짧은 단어는 유용한 정보를 담고 있지 않다고 가정
# 길이가 짧은 단어도 제거
# 모든 알파벳을 소문자로 바꿔서 단어의 개수를 줄이는 작업
