In [1]:
import numpy as np

In [2]:
A = np.array([[0,0,0,1,0,1,1,0,0],[0,0,0,1,1,0,1,0,0],[0,1,1,0,2,0,0,0,0],[1,0,0,0,0,0,0,1,1]])
print('DTM의 크기(shape) :', np.shape(A))

DTM의 크기(shape) : (4, 9)


In [3]:
U, s, VT = np.linalg.svd(A, full_matrices = True)
print('행렬 U : ')
print(U.round(2))
print('행렬 U의 크기(shape) : ', np.shape(U))

행렬 U : 
[[-0.24  0.75  0.   -0.62]
 [-0.51  0.44 -0.    0.74]
 [-0.83 -0.49 -0.   -0.27]
 [-0.   -0.    1.    0.  ]]
행렬 U의 크기(shape) :  (4, 4)


In [4]:
print('특이값 벡터 : ')
print(s.round(2))
print('특이값 벡터의 크기(shape) : ', np.shape(s))

# linalg.svd()는 특이값 분해의 결과로 대각 행렬이 아니라 특이값의 리스트를 반환
# 이를 다시 대각 행렬로 바꿔줘야 한다.

특이값 벡터 : 
[2.69 2.05 1.73 0.77]
특이값 벡터의 크기(shape) :  (4,)


In [5]:
S = np.zeros((4,9))
S[:4, :4] = np.diag(s)

print('대각 행렬 S :')
print(S.round(2))

print('대각 행렬의 크기(shape) : ')
print(np.shape(S))

대각 행렬 S :
[[2.69 0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   2.05 0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   1.73 0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.77 0.   0.   0.   0.   0.  ]]
대각 행렬의 크기(shape) : 
(4, 9)


In [6]:
print('직교행렬 VT : ')
print(VT.round(2))

print('직교 행렬 VT의 크기(shape) : ')
print(np.shape(VT))

직교행렬 VT : 
[[-0.   -0.31 -0.31 -0.28 -0.8  -0.09 -0.28 -0.   -0.  ]
 [ 0.   -0.24 -0.24  0.58 -0.26  0.37  0.58 -0.   -0.  ]
 [ 0.58 -0.    0.    0.   -0.    0.   -0.    0.58  0.58]
 [ 0.   -0.35 -0.35  0.16  0.25 -0.8   0.16 -0.   -0.  ]
 [-0.   -0.78 -0.01 -0.2   0.4   0.4  -0.2   0.    0.  ]
 [-0.29  0.31 -0.78 -0.24  0.23  0.23  0.01  0.14  0.14]
 [-0.29 -0.1   0.26 -0.59 -0.08 -0.08  0.66  0.14  0.14]
 [-0.5  -0.06  0.15  0.24 -0.05 -0.05 -0.19  0.75 -0.25]
 [-0.5  -0.06  0.15  0.24 -0.05 -0.05 -0.19 -0.25  0.75]]
직교 행렬 VT의 크기(shape) : 
(9, 9)


In [7]:
# allclose로 A행렬과 U*S*VT의 행렬이 같은지 확인
np.allclose(A, np.dot(np.dot(U,S), VT).round(2))

True

In [8]:
# t를 정하고 절단된 SVD 수행
# t=2로 가정
# 특이값 상위 2개만 보존
S = S[:2,:2]

print('대각 행렬 S :')
print(S.round(2))

대각 행렬 S :
[[2.69 0.  ]
 [0.   2.05]]


In [9]:
U = U[:,:2]
print('행렬 U :')
print(U.round(2))

행렬 U :
[[-0.24  0.75]
 [-0.51  0.44]
 [-0.83 -0.49]
 [-0.   -0.  ]]


In [10]:
VT = VT[:2,:]
print('직교행렬 VT :')
print(VT.round(2))
# V관점에서는 2개의 열만 남기고 제거한 것이 된다

직교행렬 VT :
[[-0.   -0.31 -0.31 -0.28 -0.8  -0.09 -0.28 -0.   -0.  ]
 [ 0.   -0.24 -0.24  0.58 -0.26  0.37  0.58 -0.   -0.  ]]


In [11]:
A_prime = np.dot(np.dot(U,S), VT)
print(A)
print(A_prime.round(2))

[[0 0 0 1 0 1 1 0 0]
 [0 0 0 1 1 0 1 0 0]
 [0 1 1 0 2 0 0 0 0]
 [1 0 0 0 0 0 0 1 1]]
[[ 0.   -0.17 -0.17  1.08  0.12  0.62  1.08 -0.   -0.  ]
 [ 0.    0.2   0.2   0.91  0.86  0.45  0.91  0.    0.  ]
 [ 0.    0.93  0.93  0.03  2.05 -0.17  0.03  0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.    0.  ]]


U의 각 행은 잠재의미를 표현하기 위한 수치화 된 각각의 문서 벡터
VT의 각 열은 잠재 의미를 표현하기 위한 수치화 된 각각의 단어 벡터

In [12]:
# LSA를 사용해서 문서의 수를 원하는 토픽의 수로 압축한 뒤에
# 각 토픽당 가장 중요한 단어 5개를 출력하는 실습으로 토픽 모델링 수행

In [23]:
import pandas as pd
from sklearn.datasets import fetch_20newsgroups
import nltk
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD

nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\park2\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


True

In [14]:
dataset = fetch_20newsgroups(shuffle=True, random_state=1, remove=
                             ('headers', 'footers', 'quotes'))
documents = dataset.data
print('샘플의 수 : ', len(documents))

샘플의 수 :  11314


In [15]:
# 첫번째 훈련용 샘플
# 뉴스그룹 데이터에는 특수문자가 포함된 다수의 영어문장으로 구성
# scikit-learn이 제공하는 데이터에서 target_name에는 뉴스그룹 데이터가 어떤 20개의 카테고리를
# 갖고 있었는지가 저장되어져 있음
documents[1]

"\n\n\n\n\n\n\nYeah, do you expect people to read the FAQ, etc. and actually accept hard\natheism?  No, you need a little leap of faith, Jimmy.  Your logic runs out\nof steam!\n\n\n\n\n\n\n\nJim,\n\nSorry I can't pity you, Jim.  And I'm sorry that you have these feelings of\ndenial about the faith you need to get by.  Oh well, just pretend that it will\nall end happily ever after anyway.  Maybe if you start a new newsgroup,\nalt.atheist.hard, you won't be bummin' so much?\n\n\n\n\n\n\nBye-Bye, Big Jim.  Don't forget your Flintstone's Chewables!  :) \n--\nBake Timmons, III"

In [16]:
print(dataset.target_names)

['alt.atheism', 'comp.graphics', 'comp.os.ms-windows.misc', 'comp.sys.ibm.pc.hardware', 'comp.sys.mac.hardware', 'comp.windows.x', 'misc.forsale', 'rec.autos', 'rec.motorcycles', 'rec.sport.baseball', 'rec.sport.hockey', 'sci.crypt', 'sci.electronics', 'sci.med', 'sci.space', 'soc.religion.christian', 'talk.politics.guns', 'talk.politics.mideast', 'talk.politics.misc', 'talk.religion.misc']


In [18]:
# 텍스트 전처리
# 알파벳을 제외한 구두점, 숫자, 특수문자를 제거하는 것
# 정규 표현식을 통해서 해결 가능
# 짧은 단어는 유용한 정보를 담고 있지 않다고 가정
# 길이가 짧은 단어도 제거
# 모든 알파벳을 소문자로 바꿔서 단어의 개수를 줄이는 작업

news_df = pd.DataFrame({'document' : documents})
# 특수문자 제거
news_df['clean_doc'] = news_df['document'].str.replace("[^a-zA-Z]", " ", regex=True)

# 길이가 3이하인 단어는 제거 (길이가 짧은 단어 제거)
news_df['clean_doc'] = news_df['clean_doc'].apply(lambda x : ' '.join
                                                  ([w for w in x.split() if len(w) > 3]))

# 전체 단어에 대한 소문자 변환
news_df['clean_doc'] = news_df['clean_doc'].apply(lambda x : x.lower())


In [21]:
news_df['clean_doc'][1]

# 특수문자 제거, 길이가 3이하인 단어가 제거
# 대문자가 전부 소문자로 변경된 것을 확인

'yeah expect people read actually accept hard atheism need little leap faith jimmy your logic runs steam sorry pity sorry that have these feelings denial about faith need well just pretend that will happily ever after anyway maybe start newsgroup atheist hard bummin much forget your flintstone chewables bake timmons'

In [24]:
# 뉴스그룹 데이터에서 불용어를 제거
# 불용어를 제거하기 위해 토큰화를 우선 수행
# 토큰화 -> 불용어 제거 순차적으로 진행

# NLTK로부터 불용어를 받아온다
stop_words = stopwords.words('english')
tokenized_doc = news_df['clean_doc'].apply(lambda x : x.split()) # 토큰화
tokenized_doc = tokenized_doc.apply(lambda x : [item for item in x if item not in stop_words])
# 불용어 제거

In [25]:
print(tokenized_doc[1])

# 기존에 있었던 불용어에 속하던 your, about, just, that, will, after 단어들이 사라짐
# 토큰화도 수행됨

['yeah', 'expect', 'people', 'read', 'actually', 'accept', 'hard', 'atheism', 'need', 'little', 'leap', 'faith', 'jimmy', 'logic', 'runs', 'steam', 'sorry', 'pity', 'sorry', 'feelings', 'denial', 'faith', 'need', 'well', 'pretend', 'happily', 'ever', 'anyway', 'maybe', 'start', 'newsgroup', 'atheist', 'hard', 'bummin', 'much', 'forget', 'flintstone', 'chewables', 'bake', 'timmons']


In [27]:
# tf-idf 행렬 만들기

# TfidVectorizer는 기본적으로 토큰화가 되어있지 않은 텍스트 데이터를 입력으로 사용함
# 다시 토큰화 작업을 역으로 취소하는 작업을 수행해야 함
# 역토큰화 (Dtokenization)
detokenized_doc = []
for i in range(len(news_df)):
  t = ' '.join(tokenized_doc[i])
  detokenized_doc.append(t)


news_df['clean_doc'] = detokenized_doc

In [29]:
news_df['clean_doc'][1]

'yeah expect people read actually accept hard atheism need little leap faith jimmy logic runs steam sorry pity sorry feelings denial faith need well pretend happily ever anyway maybe start newsgroup atheist hard bummin much forget flintstone chewables bake timmons'

In [30]:
# 단어에 대한 tf-idf 행렬 만들기

# 단어 1000개로 제한
vectorizer = TfidfVectorizer(stop_words='english', max_features=1000,
                             max_df=0.5, smooth_idf=True)

X = vectorizer.fit_transform(news_df['clean_doc'])

# tf-idf 행렬의 크기 확인
print('TF-IDF 행렬의 크기 : ', X.shape)

TF-IDF 행렬의 크기 :  (11314, 1000)


In [31]:
# 절단된 svd를 사용해서 차원을 축소
# 20개의 topic을 가졌다고 가정하고 토픽 모델링 시도
# topic의 숫자는 n_components의 파라미터로 지정 가능

svd_model = TruncatedSVD(n_components=20, algorithm='randomized', n_iter=100, random_state=122)

svd_model.fit(X)
len(svd_model.components_)

20

In [32]:
# svd_model.components_는 LSA에서 VT에 해당된다.
np.shape(svd_model.components_)

# 정확히 topic의 수 * 단어의 수 크기를 가짐

(20, 1000)

In [38]:
terms = vectorizer.get_feature_names_out() # 단어집합. 1000개의 단어가 저장됨

def get_topics(components, feature_names, n=5):
  for idx, topic in enumerate(components):
    print("Topic %d:" % (idx+1), 
          [(feature_names[i], topic[i].round(5)) for i in topic.argsort()[:-n-1:-1]])
    
get_topics(svd_model.components_, terms)

# 각 20개의 행의 각 1000개의 열 중 가장 값이 큰 5개의 값을 찾아서 단어로 출력

Topic 1: [('like', 0.21386), ('know', 0.20046), ('people', 0.19293), ('think', 0.17805), ('good', 0.15128)]
Topic 2: [('thanks', 0.32888), ('windows', 0.29088), ('card', 0.18069), ('drive', 0.17455), ('mail', 0.15111)]
Topic 3: [('game', 0.37064), ('team', 0.32443), ('year', 0.28154), ('games', 0.2537), ('season', 0.18419)]
Topic 4: [('drive', 0.53324), ('scsi', 0.20165), ('hard', 0.15628), ('disk', 0.15578), ('card', 0.13994)]
Topic 5: [('windows', 0.40399), ('file', 0.25436), ('window', 0.18044), ('files', 0.16078), ('program', 0.13894)]
Topic 6: [('know', 0.35228), ('like', 0.2473), ('think', 0.24323), ('windows', 0.2252), ('jesus', 0.11909)]
Topic 7: [('like', 0.67086), ('bike', 0.14236), ('chip', 0.11169), ('know', 0.11139), ('sounds', 0.10371)]
Topic 8: [('card', 0.46633), ('video', 0.22137), ('sale', 0.21266), ('monitor', 0.15463), ('offer', 0.14643)]
Topic 9: [('know', 0.46047), ('card', 0.33605), ('chip', 0.17558), ('government', 0.1522), ('video', 0.14356)]
Topic 10: [('good'

LSA의 장단점

장점
- LSA는 쉽고 빠르게 구현 가능
- 단어의 잠재적인 의미를 이끌어 낼 수 있어 문서의 유사도 계산 등에서 좋은 성능을 보여줌

단점
- SVD 특성상 이미 계산된 LSA에 새로운 데이터를 추가하여 계산하려고 하면 처음부터 다시 계산해야 함
- 새로운 정보에 대해 업데이트가 어려움

그러므로 LSA 대신 Word2Vec 등 단어의 의미를 벡터화 할 수 있는 또 다른 방법이 각광받음